name: iSOS
favicon: null
layout_spectrum: 0.69077
typography_spectrum: 0.07142
title: iSOS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fc28fc'
    - '#ffffff'
    - '#485966'
    - '#c2c4b8'
    - '#f470e8'
  brandStrength: 0.3633938126731664
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
